Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Layout/LineLength:
  Max: 1000
Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Style/ClassVars:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*'